(import (rnrs (6))
        (chez-test suite)
        (chez-test reports)
        (srfi :48)
        (test bbtrees)
        (test deques)
        (test fingertrees)
        (test hamts)
        (test heaps)
        (test psqs)
        (test queues)
        (test sequences)
        (test sets))

(define (test-all)
  (format #t "~%")
  (print-report (run-suite bbtrees))
  (print-report (run-suite deques))
  (print-report (run-suite fingertrees))
  (print-report (run-suite hamts))
  (print-report (run-suite heaps))
  (print-report (run-suite psqs))
  (print-report (run-suite queues))
  (print-report (run-suite sequences))
  (print-report (run-suite sets))
)
